# Generated by Django 5.2.5 on 2025-08-29 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_answer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="user_id",
            field=models.ForeignKey(default=0, on_delete=models.SET(0), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
